language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t alx/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alx/docker-react npm run test



